/* ════════════════════════════════════════════
   MOTS FLÉCHÉS : mots et définitions (écrits pour ce jeu)
   Format « MOT|définition » ; le mot est en majuscules sans accent, de 2 à 7 lettres.
   Les définitions restent courtes : elles s'affichent dans les cases de la grille.
════════════════════════════════════════════ */
const MF_RAW = [
  // 2 lettres
  'AN|Douze mois', 'AS|Champion', 'BU|Avalé', 'DO|Première note', 'RE|Note après do', 'MI|Troisième note',
  'FA|Quatrième note', 'LA|Sixième note', 'SI|Septième note', 'OS|Pièce du squelette', 'OU|Conjonction de choix',
  'ET|Conjonction de liaison', 'NE|Particule négative', 'NU|Sans vêtement', 'PI|Nombre 3,14', 'UN|Premier nombre',
  'TU|Sujet de la 2e personne', 'MA|Mon, au féminin', 'TA|Ton, au féminin', 'SA|Son, au féminin', 'ON|Pronom indéfini',
  'EN|Préposition de lieu', 'DE|Préposition', 'LE|Article défini', 'JE|Sujet de la 1re personne',
  'IL|Pronom masculin', 'RU|Petit ruisseau', 'RI|A éclaté de joie', 'PU|Été capable de', 'VU|Aperçu', 'LU|Parcouru',
  'EU|Possédé', 'OR|Métal jaune', 'IF|Arbre à baies rouges', 'MU|Lettre grecque après lambda',
  'NI|Négation double', 'KO|Hors de combat', 'OH|Cri de surprise', 'AH|Cri de soulagement', 'XI|Lettre grecque après nu',
  'RA|Dieu égyptien du Soleil', 'EX|Ancien partenaire', 'SU|Connu', // 3 lettres
  'ANE|Bourricot', 'AIR|Mélodie', 'AGE|Nombre d\'années', 'ART|Peinture ou musique', 'AVE|Prière à Marie',
  'BAL|On y danse', 'BAR|Débit de boissons', 'BEC|Bouche d\'oiseau', 'BIS|Une seconde fois', 'BOA|Serpent constricteur',
  'BUT|Objectif', 'CAP|Pointe de terre', 'CEP|Pied de vigne', 'CRU|Non cuit', 'DOS|Opposé du ventre',
  'DUC|Titre de noblesse', 'EAU|Elle coule du robinet', 'ETE|Saison chaude', 'FEE|Elle a une baguette magique',
  'FER|Métal du forgeron', 'FIN|Terme', 'FOI|Croyance', 'GAI|Joyeux', 'GAZ|Il alimente la cuisinière', 'GEL|Eau figée',
  'ICI|En ce lieu', 'ILE|Terre entourée d\'eau', 'IRE|Colère', 'JEU|Partie ludique', 'JUS|Boisson de fruit',
  'LAC|Étendue d\'eau', 'LIT|On y dort', 'LOI|Règle votée', 'MAL|Contraire de bien', 'MER|Elle est salée',
  'MUR|Il est de brique', 'NEZ|Il sent', 'NID|Maison d\'oiseau', 'NOM|Prénom, par exemple', 'OIE|Elle donne du foie gras',
  'OLE|Cri espagnol d\'encouragement', 'OSE|A du courage', 'OUI|Réponse positive', 'PAS|Enjambée', 'PEU|Pas beaucoup',
  'PIE|Oiseau bavard', 'PIN|Conifère', 'POT|Récipient', 'PRE|Petite prairie', 'RAT|Rongeur', 'RIZ|Céréale asiatique',
  'ROI|Souverain', 'RUE|Voie en ville', 'SAC|Contenant souple', 'SEL|Il assaisonne', 'SOL|Terrain', 'SOT|Imbécile',
  'SUD|Opposé du nord', 'TAS|Amas', 'TEL|Pareil', 'THE|Boisson chaude infusée', 'TIC|Mouvement nerveux',
  'TOI|Pronom de 2e personne', 'TON|Hauteur d\'un son', 'TOP|Signal de départ', 'TOT|De bonne heure', 'UNE|Article féminin',
  'USE|Élimé', 'VIE|Existence', 'VIN|Jus de raisin fermenté', 'VOL|Trajet en avion', 'VUE|Sens de l\'œil',
  'ZEN|Calme', 'ZOO|Jardin d\'animaux', 'AME|Esprit', 'ANS|Années', 'ARC|Il tire des flèches', 'BLE|Céréale du pain',
  'BON|De bonne qualité', 'CAR|Autocar', 'CIL|Poil de paupière', 'COQ|Mâle de la poule', 'COU|Entre tête et épaules',
  'CRI|Appel fort', 'DON|Cadeau', 'DUR|Pas mou', 'EMU|Touché', 'ERE|Période historique', 'EST|Opposé de l\'ouest',
  'FAX|Télécopie', 'FOU|Déraisonnable', 'FUT|Tonneau', 'GAG|Plaisanterie visuelle', 'GUI|Plante du baiser de Noël',
  'JET|Lancer', 'LUI|Pronom de 3e personne', 'MAI|Mois du muguet', 'MAT|Sans brillance', 'MIE|Intérieur du pain',
  'MOI|Pronom de 1re personne', 'MOT|On le lit dans un dictionnaire', 'NET|Propre', 'NUE|Dévêtue', 'OBI|Ceinture du kimono',
  'OUF|Cri de soulagement', 'PLI|Pliure', 'PUR|Sans mélange', 'QUI|Pronom interrogatif', 'RAS|Coupé court',
  'SKI|Sport de neige', 'SUC|Jus des plantes', 'TAC|Réplique du tic', 'TUE|Donne la mort', 'UNI|Sans motif',
  'VER|Il se tortille dans la terre', 'VIF|Plein d\'énergie', 'VIS|On la serre au tournevis', 'WEB|Toile mondiale',
  'YAK|Bœuf du Tibet', 'NON|Réponse négative', 'BAS|Pas haut', 'EGO|Le moi', 'EPI|Grappe de grains', 'TEE|Support de golf',
  'LES|Article pluriel', 'MES|Mon, au pluriel', 'TES|Ton, au pluriel', 'SES|Son, au pluriel', 'CES|Démonstratif pluriel',
  'RUT|Fièvre du cerf', 'SIX|Deux fois trois', 'DIX|Nombre rond', 'NEUF|Pas usagé',
  // 4 lettres
  'ACNE|Boutons d\'ado', 'AIDE|Coup de main', 'AILE|Elle sert à voler', 'AMIE|Copine', 'ANGE|Être céleste',
  'AUBE|Lever du jour', 'AVEC|Accompagné de', 'BAIE|Petit golfe', 'BAIN|Immersion dans l\'eau', 'BANC|Siège de parc',
  'BETE|Animal', 'BLEU|Couleur du ciel', 'BOIS|Matériau de la table', 'BOUE|Terre détrempée', 'BRAS|Il porte la main',
  'BRUN|Couleur du chocolat', 'CAGE|Prison d\'oiseau', 'CAFE|Boisson du matin', 'CAVE|Sous-sol', 'CHAT|Il miaule',
  'CHER|Coûteux', 'CIEL|Il est bleu ou gris', 'CLEF|Elle ouvre la porte', 'COUP|Choc', 'COUR|Espace devant la maison',
  'DAME|Pièce d\'échecs', 'DENT|Elle mord', 'DIRE|Parler', 'DOUX|Pas rude', 'DRAP|Il couvre le matelas',
  'ECHO|Il répète le son', 'ELAN|Grand cervidé', 'EPEE|Arme blanche', 'ETRE|Exister', 'FAIM|Envie de manger',
  'FETE|Réjouissance', 'FEUX|Ils passent au rouge', 'FILM|Œuvre de cinéma', 'FLAN|Dessert aux œufs', 'FOIE|Organe de la bile',
  'FOUR|Il cuit le gâteau', 'GARE|Lieu des trains', 'GANT|Il habille la main', 'GOUT|Saveur', 'GRIS|Couleur de la souris',
  'GROS|Pas mince', 'HAUT|Pas bas', 'HIER|Veille d\'aujourd\'hui', 'IDEE|Pensée', 'JADE|Pierre verte',
  'JEAN|Pantalon de toile', 'JOIE|Grand bonheur', 'JOUR|Il succède à la nuit', 'JUPE|Vêtement féminin',
  'LAIT|Boisson de la vache', 'LAME|Partie coupante du couteau', 'LENT|Pas rapide', 'LIRE|Parcourir un livre',
  'LOUP|Il hurle à la lune', 'LUNE|Satellite de la Terre', 'MAIN|Elle a cinq doigts', 'MAIS|Pourtant', 'MARE|Petit étang',
  'MIEL|Produit des abeilles', 'MOIS|Janvier ou mars', 'MONT|Grande colline', 'MORT|Fin de vie',
  'MULE|Hybride de l\'âne et de la jument', 'NAGE|Façon d\'avancer dans l\'eau', 'NOIR|Couleur de l\'ébène', 'NOTE|Do ou ré',
  'NUIT|Elle tombe le soir', 'OEUF|Il est de poule', 'ONDE|Vague', 'OURS|Plantigrade brun', 'PAIN|Baguette', 'PAIX|Contraire de guerre',
  'PARC|Jardin public', 'PATE|Mélange de farine et d\'eau', 'PEAU|Elle enveloppe le corps', 'PERE|Papa', 'PIED|Il chausse',
  'PION|Petite pièce d\'échecs', 'PLAN|Projet', 'PLUS|Davantage', 'PORT|Abri des bateaux', 'PUIS|Ensuite', 'RAGE|Fureur',
  'RAIE|Poisson plat', 'RIRE|Éclater de joie', 'RIVE|Bord de fleuve', 'ROBE|Habit de mariée', 'ROSE|Fleur épineuse',
  'ROUE|Elle tourne sous la voiture', 'RUSE|Astuce', 'SAGE|Calme et réfléchi', 'SALE|Pas propre', 'SANS|Dépourvu de',
  'SEUL|Sans compagnie', 'SOIF|Envie de boire', 'SOIN|Attention portée', 'SOIR|Fin de journée', 'SOLE|Poisson plat',
  'SOUS|Pas dessus', 'TAXI|Voiture avec chauffeur', 'TETE|Elle porte le chapeau', 'TIGE|Partie de la fleur', 'TOIT|Il couvre la maison',
  'TOUR|Édifice élevé', 'TRAM|Véhicule sur rails en ville', 'TROU|Cavité', 'TUBE|Cylindre creux', 'UNIR|Réunir',
  'VENT|Souffle de l\'air', 'VERS|Ligne de poème', 'VERT|Couleur de l\'herbe', 'VITE|Rapidement', 'VOIE|Chemin',
  'VRAI|Exact', 'YEUX|Ils voient', 'ZERO|Rien en chiffre', 'AMER|Pas sucré', 'ARME|Fusil, par exemple', 'AUTO|Voiture',
  'BEBE|Nourrisson', 'BORD|Rive', 'CAMP|Lieu de tentes', 'CASE|Carré du damier', 'CHEF|Patron', 'CIRE|Matière des bougies',
  'CITE|Grande ville', 'CLOU|On le plante au marteau', 'CODE|Suite de chiffres secrets', 'COIN|Angle', 'COTE|Os du thorax',
  'CUBE|Solide à six faces', 'DATE|Jour précis', 'DEUX|Un plus un', 'DOME|Toit arrondi', 'DONC|Par conséquent',
  'DUNE|Colline de sable', 'ETAT|Pays', 'FACE|Visage', 'FAUX|Pas vrai', 'FIER|Orgueilleux', 'FILE|Rangée de personnes',
  'FOIN|Herbe séchée', 'FORT|Costaud', 'GAIN|Bénéfice', 'GELE|Pris par la glace', 'GENS|Personnes', 'HOTE|Celui qui reçoit',
  'IRIS|Fleur ou partie de l\'œil', 'JOLI|Mignon', 'JURY|Ensemble de jurés', 'KAKI|Fruit orange', 'KILO|Mille grammes',
  'LARD|Gras du porc', 'LEGER|Pas lourd', 'LIEN|Attache', 'LIEU|Endroit', 'LOGE|Cabine d\'artiste', 'LONG|Pas court',
  'LOTO|Jeu de numéros', 'LUXE|Somptuosité', 'MAGE|Sorcier', 'MENU|Carte du restaurant', 'MINE|Galerie souterraine',
  'MODE|Tendance vestimentaire', 'MOTO|Deux-roues à moteur', 'NAIN|Petit personnage de conte', 'NOEL|Fête de décembre',
  'NORD|Direction de la boussole', 'OBUS|Projectile de canon', 'OGRE|Mangeur d\'enfants', 'ORGE|Céréale de la bière',
  'OSER|Avoir le courage', 'PAGE|Feuille de livre', 'PALE|Sans couleur', 'PEUR|Frayeur', 'PILE|Source d\'énergie',
  'PIRE|Plus mauvais', 'PLAT|Assiettée', 'POIL|Il pousse sur la peau', 'PONT|Il enjambe la rivière', 'POUR|En faveur de',
  'PRIX|Récompense', 'QUAI|Bord du port', 'RACE|Variété de chiens', 'RARE|Peu fréquent', 'RATE|Organe', 'RIEN|Néant',
  'RIME|Fin de vers', 'ROND|Cercle', 'ROUX|Couleur de cheveux', 'SAUT|Bond', 'SITE|Lieu', 'SOLO|Seul sur scène',
  'SORT|Destin', 'STOP|Panneau d\'arrêt', 'TANT|Tellement', 'TARD|Pas tôt', 'THON|Poisson en boîte', 'TRES|Fort devant un adjectif',
  'TRIO|Groupe de trois', 'TURC|Habitant d\'Ankara', 'USER|Utiliser', 'VASE|Pot à fleurs', 'VEAU|Petit de la vache',
  'VELO|Bicyclette', 'VIDE|Plein de rien', 'VISA|Autorisation d\'entrée', 'VOIR|Percevoir par les yeux', 'VOTE|Scrutin',
  'ZONE|Secteur', 'MIDI|Milieu du jour', 'IBIS|Échassier sacré', 'AMAS|Tas', 'AIRE|Surface', 'ALOE|Plante à gel',
  'ASIE|Continent du Japon', 'ATRE|Foyer de cheminée', 'AVIS|Opinion', 'BEAU|Pas laid', 'BILE|Liquide du foie',
  'BUSE|Rapace', 'CEDE|Donne', 'CHIC|Élégant', 'COLA|Boisson brune pétillante', 'CORS|Instruments de chasse',
  'EAUX|Ruisseaux ou mers', 'ECRU|Couleur naturelle', 'EGAL|Pareil', 'ELLE|Pronom féminin', 'ETAU|Outil qui serre', 'FOUS|Pièces d\'échecs', 'GENE|Unité d\'hérédité', 'HALO|Cercle de lumière',
  'IRAN|Pays de Téhéran', 'JUIN|Mois de l\'été', 'LACS|Étendues d\'eau', 'LAVE|Roche en fusion', 'LIEE|Attachée',
  'LIME|Outil qui polit', 'LOBE|Partie de l\'oreille', 'MURE|Fruit de la ronce', 'NAIF|Candide',
  'NEON|Gaz des enseignes', 'ORAL|Parlé', 'OTER|Enlever', 'PAON|Oiseau qui fait la roue', 'PORC|Cochon', 'PRET|Disposé', 'PUMA|Félin américain', 'RAME|Elle fait avancer la barque', 'REEL|Vrai',
  'RHUM|Alcool de canne', 'ROCK|Musique électrique', 'SAIN|En bonne santé', 'SEVE|Liquide des arbres', 'TACO|Galette mexicaine', 'TAIE|Enveloppe d\'oreiller', 'TOGE|Habit des juges', 'YOGA|Discipline de méditation', 'ZEBU|Bovin à bosse'
];

// 5, 6 et 7 lettres
MF_RAW.push(
  'ACIER|Fer allié au carbone', 'ADIEU|Salut définitif', 'AIGLE|Rapace royal', 'ALBUM|Livre de photos', 'ALLEE|Chemin du parc',
  'AMOUR|Sentiment tendre', 'ANGLE|Coin', 'ARBRE|Il a un tronc et des feuilles', 'ASILE|Refuge', 'ATLAS|Recueil de cartes',
  'AVION|Appareil volant', 'BALAI|Il ramasse la poussière', 'BALLE|Petite sphère de jeu', 'BARBE|Poils du menton',
  'BASSE|Voix grave', 'BIERE|Boisson du houblon', 'BISOU|Baiser d\'enfant', 'BLANC|Couleur de la neige', 'BOEUF|Animal à cornes',
  'BRAVO|Cri d\'applaudissement', 'BRUIT|Son désagréable', 'CABLE|Gros fil', 'CADRE|Bordure d\'un tableau', 'CANAL|Voie d\'eau creusée',
  'CARTE|On la bat au poker', 'CHAIR|Viande', 'CHAMP|Terre cultivée', 'CHANT|Mélodie vocale', 'CHAUD|Brûlant', 'CHIEN|Il aboie',
  'CHOIX|Option', 'CIDRE|Boisson de pomme', 'CLAIR|Pas foncé', 'CLOWN|Artiste de cirque', 'COEUR|Organe qui bat', 'COTON|Fibre blanche',
  'COURS|Leçon', 'CRAIE|Elle écrit sur le tableau', 'CREME|Dessert onctueux', 'CROIX|Symbole chrétien', 'DANSE|Bal en mouvement',
  'DEBUT|Commencement', 'DOUCE|Pas rude', 'DROIT|Pas courbe', 'ECRAN|Il affiche l\'image', 'ELEVE|Il apprend en classe',
  'ENFER|Séjour du diable', 'ENTRE|Au milieu de', 'EPAIS|Pas mince', 'ETAGE|Niveau d\'un immeuble', 'FABLE|Récit moral',
  'FAUNE|Animaux d\'une région', 'FERME|Exploitation agricole', 'FILLE|Enfant féminin', 'FLORE|Plantes d\'une région',
  'FLUTE|Instrument à vent', 'FOULE|Grand nombre de gens', 'FRAIS|Pas chaud', 'FRERE|Fils des mêmes parents', 'FRUIT|Pomme ou poire',
  'FUMEE|Elle sort de la cheminée', 'GENOU|Articulation de la jambe', 'GLACE|Eau durcie', 'GRAIN|Semence', 'GRAND|Pas petit',
  'GRAVE|Sérieux', 'GREVE|Arrêt collectif de travail', 'GUIDE|Il montre le chemin', 'HEROS|Personnage courageux',
  'HIBOU|Rapace nocturne', 'HIVER|Saison froide', 'HOTEL|On y loue une chambre', 'HUILE|Liquide gras', 'IMAGE|Illustration',
  'JAUNE|Couleur du citron', 'JEUNE|Pas vieux', 'JOUET|Objet d\'enfant', 'JUGER|Rendre la justice', 'LAINE|Toison du mouton',
  'LAPIN|Il aime les carottes', 'LARGE|Pas étroit', 'LAVER|Nettoyer à l\'eau', 'LIVRE|Il contient des pages', 'LOURD|Pas léger',
  'MAGIE|Art des illusions', 'MAIRE|Premier de la commune', 'MANGE|Il se nourrit', 'MARIN|Homme de la mer', 'MENER|Conduire',
  'MERCI|Mot de gratitude', 'METAL|Fer ou cuivre', 'MUSEE|On y expose des œuvres', 'NAGER|Se déplacer dans l\'eau', 'NEIGE|Flocons blancs',
  'NOBLE|Aristocrate', 'NOYAU|Cœur du fruit', 'OCEAN|Immense étendue salée', 'OMBRE|Zone sans soleil', 'ORAGE|Tempête avec tonnerre',
  'OUEST|Où le soleil se couche', 'OUTIL|Marteau ou tournevis', 'PARIS|Capitale de la France', 'PAUSE|Courte interruption',
  'PERLE|Bijou de l\'huître', 'PETIT|Pas grand', 'PHARE|Tour qui guide les navires', 'PIANO|Instrument à touches',
  'PISTE|Chemin de ski', 'PLAGE|Bord de mer sablonneux', 'PLUIE|Eau du ciel', 'PLUME|Elle orne l\'oiseau', 'POIDS|Il se mesure en kilos',
  'POINT|Fin de phrase', 'POMME|Fruit du pommier', 'PORTE|On la ferme à clé', 'POULE|Pondeuse', 'PRIER|S\'adresser à Dieu',
  'PROIE|Victime du chasseur', 'QUAND|À quel moment', 'RADIO|Poste qui diffuse', 'REINE|Épouse du roi', 'RIVAL|Concurrent',
  'ROBOT|Machine humanoïde', 'ROUGE|Couleur du sang', 'ROUTE|Elle mène d\'une ville à l\'autre', 'ROYAL|Digne d\'un roi',
  'SABLE|Grains de la plage', 'SAUCE|Elle accompagne les pâtes', 'SCENE|Plateau du théâtre', 'SERRE|Abri vitré pour les plantes',
  'SIGNE|Indice ou geste', 'SINGE|Primate malin', 'SOEUR|Fille des mêmes parents', 'SOLDE|Reste à payer', 'SONGE|Rêve',
  'SORTE|Genre', 'SOURD|Qui entend mal', 'SPORT|Football ou tennis', 'SUCRE|Il adoucit le café', 'SUPER|Génial',
  'TABLE|Meuble pour manger', 'TAIRE|Ne pas dire', 'TALON|Arrière du pied', 'TAUPE|Elle creuse des galeries', 'TERRE|Notre planète',
  'TIGRE|Félin rayé', 'TITRE|Nom d\'un livre', 'TOILE|Tissu du peintre', 'TOMBE|Sépulture', 'TORSE|Haut du corps',
  'TRAIN|Convoi ferroviaire', 'TRAIT|Ligne tracée', 'TRONC|Corps de l\'arbre', 'USINE|Fabrique', 'VACHE|Elle donne du lait',
  'VALSE|Danse à trois temps', 'VERRE|On y boit', 'VIDEO|Film sur écran', 'VIEUX|Pas jeune', 'VIRUS|Agent de la grippe',
  'VOILE|Tissu du bateau', 'ZEBRE|Équidé rayé', 'HAMAC|Lit suspendu', 'LIBRE|Pas prisonnier', 'DOUZE|Une douzaine', 'TIEDE|Ni chaud ni froid',
  'IDEAL|Parfait', 'VAGUE|Elle roule sur la mer', 'SOUPE|Potage', 'UTILE|Qui sert', 'FIBRE|Filament', 'OPERA|Chant et orchestre',
  'ECOLE|Lieu d\'apprentissage', 'ENFIN|Pour terminer', 'FLEUR|Rose ou tulipe', 'JAMBE|Elle porte le genou', 'MATIN|Début de journée',
  'MUET|Qui ne parle pas', 'NUAGE|Il flotte dans le ciel', 'PAIRE|Deux objets assortis', 'PANDA|Ours noir et blanc', 'PIZZA|Galette italienne',
  'POIRE|Fruit en forme de goutte', 'SEUIL|Pas de la porte', 'TACHE|Marque de saleté', 'TEMPS|Il passe ou il fait beau', 'TONNE|Mille kilos',
  'DOIGT|Il y en a cinq à la main', 'HERBE|Verdure du pré', 'PLEIN|Rempli', 'ROCHE|Pierre de la montagne',
  // 6 lettres
  'ARGENT|Métal blanc ou monnaie', 'BATEAU|Il flotte sur l\'eau', 'BOUCHE|Elle parle', 'BREBIS|Femelle du mouton', 'BUREAU|Table de travail',
  'CAMION|Poids lourd', 'CANARD|Il fait coin-coin', 'CHAISE|Siège à dossier', 'CHEMIN|Sentier', 'CIGARE|Havane', 'CLASSE|Salle d\'école',
  'COCHON|Porc', 'DESSIN|Croquis', 'DOMINO|Pièce à points', 'DRAGON|Monstre cracheur de feu', 'ENFANT|Petit d\'homme', 'ETOILE|Astre de la nuit',
  'FIEVRE|Température élevée', 'FLEUVE|Grand cours d\'eau', 'FOURMI|Insecte travailleur', 'GARCON|Enfant masculin', 'GATEAU|Dessert d\'anniversaire',
  'GAUCHE|Opposé de droite', 'GENIE|Esprit de la lampe', 'GIRAFE|Animal au long cou', 'JARDIN|Espace de fleurs', 'JOUEUR|Il participe au jeu',
  'LEGUME|Carotte ou poireau', 'MAISON|Habitation', 'MARCHE|Lieu de vente en plein air', 'MASQUE|Visage factice', 'MIROIR|Il reflète l\'image',
  'MOTEUR|Il fait tourner la voiture', 'MOUCHE|Insecte qui bourdonne', 'MOUTON|Il donne sa laine', 'NIVEAU|Étage ou hauteur', 'OISEAU|Il a des plumes',
  'ORANGE|Fruit ou couleur', 'PAPIER|Feuille de cahier', 'PARENT|Père ou mère', 'PIRATE|Forban des mers', 'PLANTE|Végétal', 'POISON|Substance mortelle',
  'PRINCE|Fils du roi', 'RACINE|Partie souterraine du végétal', 'RAISIN|Fruit de la vigne', 'REGARD|Coup d\'œil', 'RENARD|Goupil',
  'ROCHER|Grosse pierre', 'SALADE|Verte ou composée', 'SOLEIL|Astre du jour', 'SOURIS|Rongeur gris', 'SUJET|Thème', 'TIROIR|Partie coulissante du meuble',
  'TOMATE|Fruit rouge du potager', 'TORTUE|Reptile à carapace', 'TUNNEL|Passage sous la montagne', 'TULIPE|Fleur de Hollande', 'VALISE|Bagage',
  'VIOLON|Instrument à archet', 'VISAGE|Figure', 'VOYAGE|Déplacement lointain', 'BALCON|Plate-forme d\'une façade', 'BANANE|Fruit jaune',
  'BERGER|Il garde les moutons', 'BOUGIE|Chandelle', 'BOUTON|Il ferme la chemise', 'CHARME|Attrait', 'COURSE|Compétition de vitesse', 'CRAYON|Il écrit en gris',
  'DANGER|Risque', 'EPAULE|Haut du bras', 'FIGURE|Visage', 'LIMITE|Frontière', 'MARRON|Couleur de châtaigne', 'MINUTE|Soixante secondes',
  'MODELE|Exemple à suivre', 'MOTIF|Dessin répété', 'NATURE|Campagne', 'PAYSAN|Cultivateur', 'PIERRE|Caillou', 'POLICE|Force de l\'ordre', 'POTAGE|Soupe',
  'QUARTZ|Cristal de roche', 'RAISON|Bon sens', 'REPAS|Déjeuner ou dîner', 'ROMAIN|Citoyen de l\'ancienne Rome', 'RUBAN|Bande de tissu', 'SAISON|Été ou hiver',
  'SALLE|Pièce d\'une maison', 'SAMEDI|Jour avant dimanche', 'SOURCE|Naissance d\'un ruisseau', 'TAPIS|Il couvre le sol', 'TRESOR|Butin de pirate',
  'VOLEUR|Il dérobe', 'VOLCAN|Montagne qui crache de la lave', 'ZEPHYR|Brise légère', 'CHEVAL|Monture', // 7 lettres
  'ABEILLE|Insecte à miel', 'ARMOIRE|Grand meuble de chambre', 'BALEINE|Plus grand mammifère marin', 'CHATEAU|Demeure fortifiée',
  'CUISINE|Pièce où l\'on prépare les repas', 'DOCTEUR|Médecin', 'FAMILLE|Parents et enfants', 'FENETRE|Elle donne sur l\'extérieur',
  'FROMAGE|Camembert ou brie', 'GALAXIE|Voie lactée', 'GRENIER|Étage sous le toit', 'INSECTE|Fourmi ou mouche', 'LICORNE|Cheval légendaire à corne',
  'LUMIERE|Clarté', 'MEDECIN|Soigneur', 'MUSIQUE|Art des sons', 'OREILLE|Elle entend', 'PEINTRE|Artiste de la toile', 'PLANETE|Mars ou Vénus',
  'PLANCHE|Morceau de bois plat', 'POISSON|Il nage', 'POMPIER|Il éteint les feux', 'PRAIRIE|Grand pré', 'RIVIERE|Cours d\'eau', 'SERPENT|Reptile sans pattes',
  'SILENCE|Absence de bruit', 'SORCIER|Magicien maléfique', 'SOURIRE|Rictus aimable', 'TABLEAU|Œuvre accrochée', 'THEATRE|Lieu de pièces',
  'TRAVAIL|Labeur', 'VOITURE|Automobile', 'VILLAGE|Petite commune', 'CHAPEAU|Coiffe'
);
